window.__HOPE_RAID_CONFIG = {
  FIREBASE_API_KEY: "",
  FIREBASE_AUTH_DOMAIN: "",
  FIREBASE_PROJECT_ID: "",
  FIREBASE_STORAGE_BUCKET: "",
  FIREBASE_MESSAGING_SENDER_ID: "",
  FIREBASE_APP_ID: "",
  APP_SITE_TITLE: "Hope Raid Tracker",
  APP_ADMIN_UIDS: "",
  APP_DISCORD_INVITE_URL: "https://discord.gg/xYtxu6Yj"
};
